name: Build Windows

on:
  workflow_dispatch: # 手动触发
  push:
    branches: [main, master]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Package for Windows
        run: npm run package -- --platform=win32 --arch=x64

      - name: Make distributables (optional)
        run: npm run make -- --platform=win32 --arch=x64
        continue-on-error: true

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: chrome-mcp-controller-windows
          path: |
            out/**/*
          retention-days: 30
